### ISSUE TITLE
Claims should be case sensitive

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/themis#60]
Claims placed in configuration are being modified to be all lowercase.

Example of configuration:
```
      claims:
        aB:
          value: 
            aP: ["meep"]
```
Resulting JWT snippet:
```
  "ab": {
    "ap": [
      "meep"
    ],
```

according to RFC, these things should be case sensitive:
https://tools.ietf.org/html/rfc7519#section-10.1.1
